IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'artists')
BEGIN
	CREATE TABLE artists (
		artist_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID()
	,	artist_name VARCHAR(MAX)
	)
END
GO

INSERT INTO artists (artist_name) VALUES ('Sentenced')
INSERT INTO artists (artist_name) VALUES ('Type O Negative')
INSERT INTO artists (artist_name) VALUES ('Neuraxis')
INSERT INTO artists (artist_name) VALUES ('Children of Bodom')
INSERT INTO artists (artist_name) VALUES ('Nile')
INSERT INTO artists (artist_name) VALUES ('Edge of Sanity')
INSERT INTO artists (artist_name) VALUES ('Red Sparowes')
INSERT INTO artists (artist_name) VALUES ('Intestine Baalism')
INSERT INTO artists (artist_name) VALUES ('Vintersorg')
INSERT INTO artists (artist_name) VALUES ('Centinex')
INSERT INTO artists (artist_name) VALUES ('Yes')
INSERT INTO artists (artist_name) VALUES ('Sacred Reich')
INSERT INTO artists (artist_name) VALUES ('Impious')
INSERT INTO artists (artist_name) VALUES ('Disfigurement')
INSERT INTO artists (artist_name) VALUES ('Forbidden')
INSERT INTO artists (artist_name) VALUES ('Overkill')
INSERT INTO artists (artist_name) VALUES ('Eucharist')
INSERT INTO artists (artist_name) VALUES ('Steel Prophet')
INSERT INTO artists (artist_name) VALUES ('Orphanage')
INSERT INTO artists (artist_name) VALUES ('The Haunted')
INSERT INTO artists (artist_name) VALUES ('Destruction')
INSERT INTO artists (artist_name) VALUES ('In Flames')
INSERT INTO artists (artist_name) VALUES ('Terrorizer')
INSERT INTO artists (artist_name) VALUES ('Pestilence')
INSERT INTO artists (artist_name) VALUES ('Pan.Thy.Monium')